name: Single Input Android Debug APK

on:
  workflow_dispatch:
    inputs:
      tramline-input:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Tramline
      id: tramline
      uses: tramlinehq/deploy-action@main
      with:
        input: ${{ github.event.inputs.tramline-input }}

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
        cache: 'gradle'

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'
        cache: true

    - run: flutter pub get

    - run: flutter --version

    - name: Get the output
      run: |
        echo "vcode: ${{ steps.tramline.outputs.version_code }}"
        echo "vname: ${{ steps.tramline.outputs.version_name }}"
        echo "cref: ${{ steps.tramline.outputs.commit_ref }}"
        echo "cref: ${{ steps.tramline.outputs.build_notes }}"

    - run: flutter build apk --debug --build-number=${{ steps.tramline.outputs.version_code }} --build-name=${{ steps.tramline.outputs.version_name }} --flavor prod

    - uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-prod-debug.apk

  another:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Tramline
      id: tramline
      uses: tramlinehq/deploy-action@v0.1.6
      with:
        input: ${{ github.event.inputs.tramline-input }}

    - name: Get the output
      run: |
        echo "vcode: ${{ steps.tramline.outputs.version_code }}"
        echo "vname: ${{ steps.tramline.outputs.version_name }}"
        echo "cref: ${{ steps.tramline.outputs.commit_ref }}"
        echo "cref: ${{ steps.tramline.outputs.build_notes }}"

    - name: Fail randomly
      run: |
        echo "This will fail randomly"
        exit $((RANDOM % 2))
